#ifndef ANDROID_MUGEN_CPU_CORE_WORKAROUND_H
#define ANDROID_MUGEN_CPU_CORE_WORKAROUND_H

typedef enum STRING_OP {
	STR_OUTSB=0,STR_OUTSW,STR_OUTSD,
	STR_INSB=4,STR_INSW,STR_INSD,
	STR_MOVSB=8,STR_MOVSW,STR_MOVSD,
	STR_LODSB=12,STR_LODSW,STR_LODSD,
	STR_STOSB=16,STR_STOSW,STR_STOSD,
	STR_SCASB=20,STR_SCASW,STR_SCASD,
	STR_CMPSB=24,STR_CMPSW,STR_CMPSD
} STRING_OP;

typedef enum STRING_OP StringOps;

#endif
